<?php

namespace Proxies\__CG__\Challenkers\MainBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Membres extends \Challenkers\MainBundle\Entity\Membres implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Challenkers\\MainBundle\\Entity\\Membres' . "\0" . 'id', '' . "\0" . 'Challenkers\\MainBundle\\Entity\\Membres' . "\0" . 'pseudo', '' . "\0" . 'Challenkers\\MainBundle\\Entity\\Membres' . "\0" . 'level', '' . "\0" . 'Challenkers\\MainBundle\\Entity\\Membres' . "\0" . 'classe', '' . "\0" . 'Challenkers\\MainBundle\\Entity\\Membres' . "\0" . 'points', '' . "\0" . 'Challenkers\\MainBundle\\Entity\\Membres' . "\0" . 'idGuilde', '' . "\0" . 'Challenkers\\MainBundle\\Entity\\Membres' . "\0" . 'idServeur');
        }

        return array('__isInitialized__', '' . "\0" . 'Challenkers\\MainBundle\\Entity\\Membres' . "\0" . 'id', '' . "\0" . 'Challenkers\\MainBundle\\Entity\\Membres' . "\0" . 'pseudo', '' . "\0" . 'Challenkers\\MainBundle\\Entity\\Membres' . "\0" . 'level', '' . "\0" . 'Challenkers\\MainBundle\\Entity\\Membres' . "\0" . 'classe', '' . "\0" . 'Challenkers\\MainBundle\\Entity\\Membres' . "\0" . 'points', '' . "\0" . 'Challenkers\\MainBundle\\Entity\\Membres' . "\0" . 'idGuilde', '' . "\0" . 'Challenkers\\MainBundle\\Entity\\Membres' . "\0" . 'idServeur');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Membres $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPseudo($pseudo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPseudo', array($pseudo));

        return parent::setPseudo($pseudo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPseudo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPseudo', array());

        return parent::getPseudo();
    }

    /**
     * {@inheritDoc}
     */
    public function setLevel($level)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLevel', array($level));

        return parent::setLevel($level);
    }

    /**
     * {@inheritDoc}
     */
    public function getLevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLevel', array());

        return parent::getLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setClasse($classe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClasse', array($classe));

        return parent::setClasse($classe);
    }

    /**
     * {@inheritDoc}
     */
    public function getClasse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClasse', array());

        return parent::getClasse();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoints($points)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoints', array($points));

        return parent::setPoints($points);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoints()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoints', array());

        return parent::getPoints();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdGuilde($idGuilde)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdGuilde', array($idGuilde));

        return parent::setIdGuilde($idGuilde);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdGuilde()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdGuilde', array());

        return parent::getIdGuilde();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdServeur($idServeur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdServeur', array($idServeur));

        return parent::setIdServeur($idServeur);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdServeur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdServeur', array());

        return parent::getIdServeur();
    }

}
