<?php

namespace Challenkers\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GuildeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuildeRepository extends EntityRepository
{
}
