<?php

namespace Challenkers\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MembresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembresRepository extends EntityRepository
{
    public function findRankS($idGuilde)
    {
     return $this->getEntityManager()
            ->createQuery(
                'SELECT m FROM ChallenkersMainBundle:Membres m where m.points>700 and m.idGuilde='.$idGuilde
            )
            ->getResult();
    }
    
    public function findRankA($idGuilde)
    {
     return $this->getEntityManager()
            ->createQuery(
                'SELECT m FROM ChallenkersMainBundle:Membres m where m.points>500 and m.points<700 and m.idGuilde='.$idGuilde
            )
            ->getResult();
    }
    
    public function findRankB($idGuilde)
    {
     return $this->getEntityManager()
            ->createQuery(
                'SELECT m FROM ChallenkersMainBundle:Membres m where m.points>300 and m.points<500 and m.idGuilde='.$idGuilde
            )
            ->getResult();
    }
    
    public function findRankC($idGuilde)
    {
     return $this->getEntityManager()
            ->createQuery(
                'SELECT m FROM ChallenkersMainBundle:Membres m where m.points<300 and m.idGuilde='.$idGuilde
            )
            ->getResult();
    }
}
